# Generated by Django 4.1.1 on 2023-04-26 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departmentmaster',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_at_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_by_date', models.DateField(null=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empweb.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartmentmaster',
            fields=[
                ('sub_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_department_name', models.CharField(max_length=110)),
                ('description', models.CharField(max_length=100)),
                ('created_at_date', models.DateField(auto_now_add=True)),
                ('updated_by_date', models.DateField(null=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empweb.departmentmaster')),
                ('updated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('join_date', models.DateField()),
                ('created_at_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('emp_no', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('emp_start_date', models.DateField(null=True)),
                ('emp_end_date', models.DateField(null=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empweb.departmentmaster')),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empweb.subdepartmentmaster')),
                ('updated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
